Update .github/workflows/master-e2e.yaml
Co-authored-by: Tomas Hehejik <thehejik@suse.com>
Signed-off-by: Chandan Pinjani <chandan.pinjani@suse.com>

diff --git a/.github/workflows/master-e2e.yaml b/.github/workflows/master-e2e.yaml
--- a/.github/workflows/master-e2e.yaml
+++ b/.github/workflows/master-e2e.yaml
@@ -556,17 +556,14 @@ jobs:
       - name: Set Rancher Manager version for Migration
         if: ${{ contains(inputs.grep_test_by_tag, '@migration') }}
         run: |
-          # Check if Rancher Version input is equal to nightly run version
-          if [[ "${{ inputs.rancher_version }}" != "head/2.15" ]]; then
-            # Check if Rancher Version input is valid for migration
-            if [[ "${{ inputs.rancher_version }}" != *"2.13"* ]]; then
-              echo "ERROR: Migration is only allowed to 2.13 Rancher Version"
-              exit 1
-            else
-              echo "RANCHER_VERSION=${{ inputs.rancher_version }}" >> ${GITHUB_ENV}
-            fi
+          VERSION="${{ inputs.rancher_version }}"
+          if [[ "$VERSION" == *"2.13"* ]]; then
+            echo "RANCHER_VERSION=$VERSION" >> "$GITHUB_ENV"
+          elif [[ "$VERSION" == head/* ]]; then
+            echo "RANCHER_VERSION=head/2.13" >> "$GITHUB_ENV"
           else
-            echo "RANCHER_VERSION=head/2.13" >> ${GITHUB_ENV}
+            echo "ERROR: Migration is only allowed to 2.13 Rancher Version"
+            exit 1
           fi
       - name: Set Rancher Manager version for Upgrade
         if: ${{ contains(inputs.grep_test_by_tag, '@upgrade') }}
