Upgrade 2.15
Signed-off-by: Chandan Pinjani <chandan.pinjani@suse.com>

diff --git a/.github/workflows/master-e2e.yaml b/.github/workflows/master-e2e.yaml
--- a/.github/workflows/master-e2e.yaml
+++ b/.github/workflows/master-e2e.yaml
@@ -82,7 +82,10 @@ on:
         default: https://raw.githubusercontent.com/rancherlabs/support-tools/master/collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
         type: string
       rancher_version:
-        description: Rancher Manager channel/version/head_version to use for installation
+        description: Rancher Manager version to use for installation
+        type: string
+      rancher_upgrade_version:
+        description: Rancher Manager version to use for upgrade
         type: string
       turtles_dev_chart:
         description: Install rancher turtles dev chart
@@ -330,7 +333,47 @@ jobs:
           curl -sk https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz -o helm.tar.gz
           echo "${HELM_SHA256}  helm.tar.gz" | sha256sum -c -
           sudo tar -xzf helm.tar.gz --strip-components=1 -C /usr/local/bin/ linux-amd64/helm && rm helm.tar.gz
-      - name: Set Rancher Manager Install version
+
+      - name: Set Rancher Manager version for Pre-Migration
+        if: ${{ contains(inputs.grep_test_by_tag, '@migration') }}
+        run: |
+          echo "COMMON_SPECS=$(echo "${{ env.SPECS }}" | tr '\n' ' ')" >> ${GITHUB_ENV}
+          echo "SPECS=" >> ${GITHUB_ENV}
+          RANCHER_VERSION="${{ inputs.rancher_version }}"
+          # Pre-Migration
+          if [[ "$RANCHER_VERSION" == *"2.12"* ]]; then
+            echo "RANCHER_VERSION=$RANCHER_VERSION" >> "$GITHUB_ENV"
+          elif [[ "$VERSION" == head/* ]]; then
+            # Default version for pre-migration tests
+            echo "RANCHER_VERSION=head/2.12" >> "$GITHUB_ENV"
+          else
+            echo "ERROR: Migration is only allowed from 2.12 Rancher Version"
+            exit 1
+          fi
+
+      - name: Set Rancher Manager version for Pre-Upgrade
+        if: ${{ contains(inputs.grep_test_by_tag, '@upgrade') }}
+        run: |
+          echo "COMMON_SPECS=$(echo "${{ env.SPECS }}" | tr '\n' ' ')" >> ${GITHUB_ENV}
+          RANCHER_VERSION="${{ inputs.rancher_version }}"
+          # Pre-Upgrade
+          if [[ "$RANCHER_VERSION" == *"2.13"* || "$RANCHER_VERSION" == *"2.14"* ]]; then
+            echo "RANCHER_VERSION=$RANCHER_VERSION" >> "$GITHUB_ENV"
+          elif [[ "$VERSION" == head/* ]]; then
+            # Default version for pre-upgrade tests
+            echo "RANCHER_VERSION=head/2.14" >> "$GITHUB_ENV"
+          else
+            echo "ERROR: Upgrade is only allowed from 2.13, 2.14 Rancher Version"
+            exit 1
+          fi
+
+      - name: Set Rancher Manager version for Installation
+        if: ${{ contains(inputs.grep_test_by_tag, '@short') || contains(inputs.grep_test_by_tag, '@full') || contains(inputs.grep_test_by_tag, '@vsphere') }}
+        run: |
+          # Default version for tests
+          echo "RANCHER_VERSION=${{ inputs.rancher_version }}" >> ${GITHUB_ENV}
+
+      - name: Set Rancher Manager version for Installation
         run: |
           if [[ "${{ inputs.grep_test_by_tag }}" =~ "@migration" ]]; then
             # Required for migration tests
@@ -385,7 +428,7 @@ jobs:
       # Checkout into r/turtles repo if dev=true to build turtles and providers chart;
       # or if it's a migration test, then to copy the provider migration script
       - name: Check out rancher/turtles repo
-        if: ${{ inputs.turtles_dev_chart == true || contains(inputs.grep_test_by_tag, '@migration') || contains(inputs.grep_test_by_tag, '@upgrade') }}
+        if: ${{ inputs.turtles_dev_chart == true || contains(inputs.grep_test_by_tag, '@migration') }}
         uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
         with:
           repository: ${{ env.TURTLES_REPO }}
@@ -433,7 +476,7 @@ jobs:
           # Note allow port tcp/4080 by a firewall rule on GCP
           docker run --name git-http-backend -d -p 4080:80 -v /tmp/system-charts:/git ynohat/git-http-backend
 
-      - name: Copy Migration Script (to be run after migration from <=2.12 to >=2.13)
+      - name: Copy Migration Script (to be run after migration from 2.12 to 2.13)
         if: ${{ contains(inputs.grep_test_by_tag, '@migration') }}
         run: |
           # Migration script from rancher/turtles
@@ -550,28 +593,34 @@ jobs:
             QASE_TESTOPS_RUN_ID=$(cat tests/cypress/latest/QASE_TESTOPS_RUN_ID.txt)
             echo "qase_run_id=${QASE_TESTOPS_RUN_ID}" >> ${GITHUB_OUTPUT}
           fi
-      - name: Set Rancher Manager version for Migration
+      - name: Set Rancher Manager version for Post-Migration
         if: ${{ contains(inputs.grep_test_by_tag, '@migration') }}
         run: |
-          VERSION="${{ inputs.rancher_version }}"
-          if [[ "$VERSION" == *"2.13"* ]]; then
-            echo "RANCHER_VERSION=$VERSION" >> "$GITHUB_ENV"
+          RANCHER_UPGRADE_VERSION="${{ inputs.rancher_upgrade_version }}"
+          # Post-Migration
+          if [[ "$RANCHER_UPGRADE_VERSION" == *"2.13"* ]]; then
+            echo "RANCHER_VERSION=$RANCHER_UPGRADE_VERSION" >> "$GITHUB_ENV"
           elif [[ "$VERSION" == head/* ]]; then
+            # Default version for post-migration tests
             echo "RANCHER_VERSION=head/2.13" >> "$GITHUB_ENV"
           else
             echo "ERROR: Migration is only allowed to 2.13 Rancher Version"
             exit 1
           fi
-      - name: Set Rancher Manager version for Upgrade
+      - name: Set Rancher Manager version for Post-Upgrade
         if: ${{ contains(inputs.grep_test_by_tag, '@upgrade') }}
         run: |
-          VERSION="${{ inputs.rancher_version }}"
-          if [[ "$VERSION" == *"2.14"* ]]; then
-            echo "RANCHER_VERSION=$VERSION" >> "$GITHUB_ENV"
-          elif [[ "$VERSION" == head/* ]]; then
-            echo "RANCHER_VERSION=head/2.14" >> "$GITHUB_ENV"
+          RANCHER_VERSION="${{ inputs.rancher_version }}"
+          RANCHER_UPGRADE_VERSION="${{ inputs.rancher_upgrade_version }}"
+          if [[ "$RANCHER_VERSION" == *"2.13"* && "$RANCHER_UPGRADE_VERSION" == *"2.14"* ]]; then
+            echo "RANCHER_VERSION=$RANCHER_UPGRADE_VERSION" >> "$GITHUB_ENV"
+          elif [[ "$RANCHER_VERSION" == *"2.14"* && "$RANCHER_UPGRADE_VERSION" == *"2.15"* ]]; then
+            echo "RANCHER_VERSION=$RANCHER_UPGRADE_VERSION" >> "$GITHUB_ENV"
+          elif [ -z "$RANCHER_UPGRADE_VERSION" ]; then
+            # Default version for post-upgrade tests
+            echo "RANCHER_VERSION=head/2.15" >> "$GITHUB_ENV"
           else
-            echo "ERROR: Upgrade is only allowed to 2.14 Rancher Version"
+            echo "ERROR: Upgrade is only allowed to 2.14, 2.15 Rancher Versions"
             exit 1
           fi
       - name: Upgrade Rancher Manager
